name: MORL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1u
  - pip=22.3.1
  - python=3.7.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - about-time==4.2.1
    - absl-py==1.4.0
    - alive-progress==3.1.5
    - appdirs==1.4.4
    - autograd==1.6.2
    - cachetools==5.3.1
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==1.2.2
    - cma==3.2.2
    - cycler==0.11.0
    - cython==0.29.35
    - deprecated==1.2.14
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - farama-notifications==0.0.4
    - fasteners==0.18
    - fastrand==1.8.0
    - fonttools==4.38.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - glfw==2.6.0
    - google-auth==2.20.0
    - google-auth-oauthlib==0.4.6
    - grapheme==0.6.0
    - grpcio==1.56.0
    - gym==0.15.3
    - gymnasium==0.28.1
    - idna==3.4
    - imageio==2.31.1
    - importlib-metadata==6.7.0
    - jax-jumpy==1.0.0
    - jsonpatch==1.33
    - jsonpointer==2.4
    - kiwisolver==1.4.4
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.5.3
    - mujoco-py==2.0.2.9
    - networkx==2.6.3
    - numpy==1.21.6
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - packaging==23.1
    - pathtools==0.1.2
    - pillow==9.5.0
    - platformdirs==4.0.0
    - protobuf==3.20.3
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pygame==2.6.0
    - pyglet==1.3.2
    - pymoo==0.6.0
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rltorch==0.1.0
    - rsa==4.9
    - scipy==1.7.3
    - sentry-sdk==2.24.1
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torch==1.3.1
    - tornado==6.2
    - typing-extensions==4.7.1
    - urllib3==1.26.16
    - visdom==0.2.4
    - wandb==0.18.7
    - websocket-client==1.6.1
    - werkzeug==2.2.3
    - wrapt==1.16.0
    - zipp==3.15.0
prefix: /home/lpy/anaconda3/envs/MORL
